/**
 * Auto-generated base types for Neos ContentApi data
 * Generated by: ddev app-neos-next-flow visol.neos.zebraschemagenerator:schema:generateinterfaces
 */

/** Image data as returned by Networkteam.Neos.ContentApi */
export interface NeosImageData {
  src: string
  width: number
  height: number
  title?: string
  caption?: string
  copyrightNotice?: string
  byteSize: number
  fileName: string
  fileExtension: string
  lastModified: string
}

/** Asset data as returned by Networkteam.Neos.ContentApi */
export interface NeosAssetData {
  src: string
  title?: string
  caption?: string
  copyrightNotice?: string
  byteSize: number
  fileName: string
  fileExtension: string
  lastModified: string
}

/** Generic node reference (when target type is unknown) */
export interface NeosNodeReference {
  identifier: string
  nodeType: string
  properties: Record<string, unknown>
}

/**
 * Referenced document node as returned by Networkteam.Neos.ContentApi (>= 0.13): the properties
 * of the target node type plus its identifier, node type and URI.
 */
export type NeosReferencedDocument<T = Record<string, unknown>> = T & {
  _identifier: string
  _nodeType: string
  /** Missing when no URI could be resolved (e.g. for a site without an active domain) */
  _nodeUri?: string
}

/** DateTime as serialized by PHP's JSON encoding */
export interface NeosDateTime {
  date: string
  timezone_type: number
  timezone: string
}
