/**
 * Auto-generated base types for Neos ContentApi data
 * Generated by: ddev app-neos-next-flow visol.neos.zebraschemagenerator:schema:generateinterfaces
 */

/** Image data as returned by Networkteam.Neos.ContentApi */
export interface NeosImageData {
  src: string
  width: number
  height: number
  title?: string
  caption?: string
  copyrightNotice?: string
  byteSize: number
  fileName: string
  fileExtension: string
  lastModified: string
}

/** Asset data as returned by Networkteam.Neos.ContentApi */
export interface NeosAssetData {
  src: string
  title?: string
  caption?: string
  copyrightNotice?: string
  byteSize: number
  fileName: string
  fileExtension: string
  lastModified: string
}

/** Generic node reference (when target type is unknown) */
export interface NeosNodeReference {
  identifier: string
  nodeType: string
  properties: Record<string, unknown>
}

/** DateTime as serialized by PHP's JSON encoding */
export interface NeosDateTime {
  date: string
  timezone_type: number
  timezone: string
}
